profile: light
ceip_policy_disclosed: true # Installation fails if this is set to 'false'

buildservice:
  kp_default_repository: "harbor.ryanbaker.io/bens-mini-tap/build-service"
  kp_default_repository_username: "wilcockb"
  kp_default_repository_password: "Cj7ObHx7"
  tanzunet_username: "wilcockb@vmware.com"
  tanzunet_password: "49vTqj!SXc"
  descriptor_name: "tap-1.0.0-full"
  enable_automatic_dependency_updates: true

supply_chain: basic

ootb_supply_chain_basic:
  registry:
    server: "harbor.ryanbaker.io"
    repository: "bens-mini-tap"
  gitops:
    ssh_secret: ""

tap_gui:
  service_type: ClusterIP
  ingressEnabled: "true"
  ingressDomain: "benwilcock.net"
  app_config:
    app:
      baseUrl: http://tap-gui.benwilcock.net
    catalog:
      locations:
        - type: url
          target: https://github.com/benwilcock/tap-gui-blank-catalog/blob/main/catalog-info.yaml
    backend:
      baseUrl: http://tap-gui.benwilcock.net
      cors:
        origin: http://tap-gui.benwilcock.net

metadata_store:
  app_service_type: LoadBalancer # (optional) Defaults to LoadBalancer. Change to NodePort for distributions that don't support LoadBalancer

contour:
  envoy:
    service:
      type: LoadBalancer

cnrs:
  domain_name: "apps.benwilcock.net"
