apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: node-express
  description: Node Express Sample App
  tags:
    - app-accelerator
    - node
    - express
    - rest
    - webpage
    - tanzu
  annotations:
    'backstage.io/kubernetes-label-selector': 'app.kubernetes.io/part-of=node-express'
spec:
  type: service
  lifecycle: production
  owner: mambg-tmm-team
  system: polyglot-demo-apps

---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: dotnet-aspcore
  description: .Net Core ASP Sample App
  tags:
    - dotnet
    - aspcore
    - rest
    - webpage
    - tanzu
  annotations:
    'backstage.io/kubernetes-label-selector': 'app.kubernetes.io/part-of=dotnet-aspcore'
spec:
  type: service
  lifecycle: production
  owner: mambg-tmm-team
  system: polyglot-demo-apps

---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: springboot-maven
  description: Spring Boot Sample App
  tags:
    - springboot
    - maven
    - rest
    - webpage
    - tanzu
  annotations:
    'backstage.io/kubernetes-label-selector': 'app.kubernetes.io/part-of=springboot-maven'
spec:
  type: service
  lifecycle: production
  owner: mambg-tmm-team
  system: polyglot-demo-apps

---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: python-pipenv
  description: Python Flask Sample App
  tags:
    - python
    - flask
    - rest
    - webpage
    - tanzu
  annotations:
    'backstage.io/kubernetes-label-selector': 'app.kubernetes.io/part-of=python-pipenv'
spec:
  type: service
  lifecycle: production
  owner: mambg-tmm-team
  system: polyglot-demo-apps

---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: tanzu-java-web-app
  description: Tanzu Accelerator Sample App Using Java & Spring
  tags:
    - java
    - spring
    - rest
    - tanzu
  annotations:
    'backstage.io/kubernetes-label-selector': 'app.kubernetes.io/part-of=tanzu-java-web-app'
spec:
  type: service
  lifecycle: production
  owner: mambg-tmm-team
  system: polyglot-demo-apps

---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: polyglot-demo-apps
  description: A set of technology demonstrator projects that offer similar experiences using multiple programming languages.
spec:
  owner: mambg-tmm-team
  domain: polyglot-demos

---
apiVersion: backstage.io/v1alpha1
kind: Domain
metadata:
  name: polyglot-demos
  description: Apps in many languages supported by TAP
spec:
  owner: mambg-tmm-team

# ---
# apiVersion: backstage.io/v1alpha1
# kind: Group
# metadata:
#   name: mambg-tmm-team
#   description: The Tanzu Application Platform Technical Marketing Team
# spec:
#   type: team
#   profile:
#     displayName: Tanzu Technical Marketing Team
#     email: tmm@example.com
#   children: []
#   members: [wilcockb,nickk,artf,klee]

# ---
# apiVersion: backstage.io/v1alpha1
# kind: User
# metadata:
#   name: wilcockb
# spec:
#   profile:
#     displayName: Ben Wilcock
#     email: benw@example.com
#     picture: https://tanzu.vmware.com/developer/team/ben-wilcock/images/ben-wilcock.jpg
#   memberOf: [mambg-tmm-team]

# ---
# apiVersion: backstage.io/v1alpha1
# kind: User
# metadata:
#   name: mylesg
# spec:
#   profile:
#     displayName: Myles Gray
#     email: mylesg@example.com
#     picture: https://tanzu.vmware.com/developer/team/myles-gray/images/myles-gray.jpg
#   memberOf: [mambg-tmm-team]

# ---
# apiVersion: backstage.io/v1alpha1
# kind: User
# metadata:
#   name: artf
# spec:
#   profile:
#     displayName: Art Fewell
#     email: artf@example.com
#     picture: https://tanzu.vmware.com/developer/team/art-fewell/images/art-fewell.jpg
#   memberOf: [mambg-tmm-team]

# ---
# apiVersion: backstage.io/v1alpha1
# kind: User
# metadata:
#   name: nickk
# spec:
#   profile:
#     displayName: Nick Kuhn
#     email: nickk@example.com
#     picture: https://tanzu.vmware.com/developer/team/nick-kuhn/images/nick-kuhn.jpg
#   memberOf: [mambg-tmm-team]

# ---
# apiVersion: backstage.io/v1alpha1
# kind: User
# metadata:
#   name: klee
# spec:
#   profile:
#     displayName: Keith Lee
#     email: klee@example.com
#     picture: https://images.apps-cloudmgmt.techzone.vmware.com/sites/default/files/pictures/KL_profile_220x220.jpg
#   memberOf: [mambg-tmm-team]
